# Generated by Django 5.2.8 on 2026-02-20 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_sections', 'View sections'), ('manage_sections', 'Manage sections')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='النطاق')),
            ],
            options={
                'verbose_name': 'Scope',
                'verbose_name_plural': 'Scopes',
            },
        ),
        migrations.CreateModel(
            name='ScopeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='تفعيل النطاقات')),
            ],
            options={
                'verbose_name': 'Scope Settings',
                'verbose_name_plural': 'Scope Settings',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الهاتف')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('preferences', models.JSONField(blank=True, default=dict, verbose_name='تفضيلات المستخدم')),
                ('is_email_2fa_enabled', models.BooleanField(default=False, verbose_name='2FA via Email')),
                ('is_phone_2fa_enabled', models.BooleanField(default=False, verbose_name='2FA via Phone')),
                ('is_totp_2fa_enabled', models.BooleanField(default=False, verbose_name='2FA via App')),
                ('totp_secret', models.CharField(blank=True, max_length=32, null=True, verbose_name='TOTP Secret')),
                ('backup_codes', models.JSONField(blank=True, default=list, verbose_name='Backup Codes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='microsys.scope', verbose_name='النطاق')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'permissions': [('manage_staff', 'Can manage staff')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='العملية')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='القسم')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='المستند')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='agent')),
                ('details', models.JSONField(blank=True, default=dict, null=True, verbose_name='التفاصيل')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='microsys.scope', verbose_name='النطاق')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='اسم المستخدم')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'permissions': [('view_activity_log', 'View activity log')],
                'default_permissions': (),
            },
        ),
    ]
