# Generated by Django 5.2.8 on 2026-03-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم النظام (إنجليزي)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='name',
            field=models.CharField(default='ادارة النظام', max_length=255, verbose_name='اسم النظام (عربي)'),
        ),
    ]
