# Generated by Django 5.2.8 on 2026-02-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('manage_staff', 'Can manage staff')], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Scope', 'verbose_name_plural': 'Scopes'},
        ),
        migrations.AlterModelOptions(
            name='scopesettings',
            options={'verbose_name': 'Scope Settings', 'verbose_name_plural': 'Scope Settings'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'default_permissions': (), 'managed': False, 'permissions': [('view_sections', 'View sections'), ('manage_sections', 'Manage sections')]},
        ),
        migrations.AlterModelOptions(
            name='useractivitylog',
            options={'permissions': [('view_activity_log', 'View activity log')], 'verbose_name': 'Activity Log', 'verbose_name_plural': 'Activity Logs'},
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(max_length=50, verbose_name='العملية'),
        ),
    ]
