# Generated by Django 5.2.8 on 2026-02-15 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microsys', '0002_alter_profile_options_alter_scope_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'default_permissions': (), 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='useractivitylog',
            options={'default_permissions': (), 'permissions': [('view_activity_log', 'View activity log')], 'verbose_name': 'Activity Log', 'verbose_name_plural': 'Activity Logs'},
        ),
    ]
