# Generated by Django 5.2.8 on 2026-02-15 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microsys', '0003_alter_profile_options_alter_useractivitylog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'default_permissions': (), 'permissions': [('manage_staff', 'Can manage staff')], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
