# Generated by Django 5.2.8 on 2026-02-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsys', '0004_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False, verbose_name='تفعيل المصادقة الثنائية'),
        ),
    ]
