# Generated by Django 5.2.8 on 2026-02-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsys', '0005_profile_is_2fa_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_2fa_enabled',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_email_2fa_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA via Email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_phone_2fa_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA via Phone'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_totp_2fa_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA via App'),
        ),
        migrations.AddField(
            model_name='profile',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='TOTP Secret'),
        ),
    ]
