# Generated by Django 5.2.8 on 2026-02-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsys', '0006_remove_profile_is_2fa_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list, verbose_name='Backup Codes'),
        ),
    ]
