# Generated by Django 5.2.8 on 2026-02-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsys', '0007_profile_backup_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='details',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='التفاصيل'),
        ),
    ]
